FROM tomcat:8.5-jdk11-temurin-focal

LABEL maintainer="Akanksha K Sukre"

WORKDIR /home/edureka/devops-project

ADD /target/ABCtechnologies-1.0.war /usr/local/tomcat/webapps/

EXPOSE 8080

CMD ["catalina.sh", "run"]