apiVersion: v1
kind: Service
metadata:
  name: abc-tech-svc 
  labels:
    type: webapp
spec:
  ports:
  - nodePort: 30500
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    type: webapp
  type: NodePort